### ISSUE TITLE
i cant open

### ISSUE THREAD

**Issue by luucasalves** [lucasdavid/wikiart#8]
olá, não consegui abrir o arquivo mesmo executando o arquivo, pode me dar uma ajuda?

Traceback (most recent call last):
  File "C:\Users\ \Desktop\wikiart-master\wikiart.py", line 1, in <module>
    from wikiart.console import main
  File "C:\Users\ \Desktop\wikiart-master\wikiart\console.py", line 11, in <module>
    from . import base, converter, fetcher, settings
  File "C:\Users\k \Desktop\wikiart-master\wikiart\fetcher.py", line 14, in <module>
    import requests
ImportError: No module named 'requests'

**Comment by lucasdavid** [comment]
`pip install requests` antes de executar este projeto. `python setup.py install` também vai instalar as dependências necessárias.

**Comment by luucasalves** [comment]
thanks, work now!!! thank u so much <3
